name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}  # allows manual run

jobs:
  ci:
    name: Install & Test
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Run tests (if you add Jest later)
      - name: Run tests
        run: npm test || echo "No tests defined"

      # 5️⃣ Optional: Run the server (for smoke test)
      - name: Start server (smoke test)
        run: |
          nohup node index.js &
          sleep 5
          curl http://localhost:3000

  deploy:
    name: Build & Deploy Docker
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1️⃣ Set up Docker
      - uses: docker/setup-buildx-action@v3

      # 2️⃣ Login to Docker Hub (store credentials in GitHub Secrets)
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 3️⃣ Build and push Docker image
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/express-codespaces:latest
